### ISSUE TITLE
dependencies note

### ISSUE THREAD

**Issue by sconlan** [patrickwest/PhaVa#1]
I'm installing now in a conda environment and had a couple of notes for the install.

It took me a minute to figure out einverted is part of emboss
```
conda install -c bioconda emboss
```

Not mentioned but phava complained if I didn't install pysam as a dependency
```
conda install -c bioconda pysam
```

That along with the mentioned
```
pip install biopython
conda install -c bioconda minimap2
```
and it shows the usage screen without errors

**Comment by patrickwest** [comment]
Thanks for the helpful note, I updated the readme to be more clear on the dependencies
